let strip = neopixel.create(DigitalPin.P15, 2, NeoPixelMode.RGB)
basic.forever(function () {
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Blue))
    strip.show()
    basic.pause(100)
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    basic.pause(100)
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Blue))
    strip.show()
    basic.pause(100)
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.show()
})
basic.forever(function () {
    music.playMelody("C5 G C5 G C5 G C5 G ", 120)
})
basic.forever(function () {
    cuteBot.colorLight(cuteBot.RGBLights.RGB_L, 0xff0000)
    basic.pause(200)
    cuteBot.closeheadlights()
    cuteBot.colorLight(cuteBot.RGBLights.RGB_R, 0x0000ff)
    basic.pause(200)
    cuteBot.closeheadlights()
})
