let strip = neopixel.create(DigitalPin.P15, 2, NeoPixelMode.RGB)
basic.forever(function () {
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Blue))
    strip.show()
    basic.pause(100)
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    basic.pause(100)
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Blue))
    strip.show()
    basic.pause(100)
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.show()
})
basic.forever(function () {
    music.playMelody("C5 G C5 G C5 G C5 G ", 120)
})
